version: '3.8'
# lancer avec : docker compose -f docker-compose.dev.yml --env-file .env up -d
services:
  backend:
    container_name: backend
    build:
      context: ./docker/
      dockerfile: Dockerfile-jdk
    volumes:
      - ./backend:/app
      - ./backend/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - "8082:8080"
      - "35729:35729"
      - "5005:5005"
  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      #- ./init-db:/docker-entrypoint-initdb.d
  adminer:
    container_name: adminer
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: "${ADMINER_DEFAULT_SERVER}"
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  mysql-data:
